# Generated by Django 4.2.13 on 2025-02-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_notification_menu_item_followstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='foods.store'),
        ),
        migrations.AlterField(
            model_name='likemenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.menuitem'),
        ),
        migrations.AlterField(
            model_name='likestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foods.store'),
        ),
    ]
