# Generated by Django 4.2.13 on 2025-02-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_followstore_store_alter_likemenuitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_menu_items', to='foods.menuitem'),
        ),
    ]
