# Generated by Django 4.2.13 on 2025-02-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_follow_delete_followstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowStore',
        ),
    ]
